connection:
  server: fumbbl.com
  port: 22223
  compression: true

zmq:
  senderEndpoint: tcp://localhost:44445
  receiverEndpoint: tcp://localhost:44444
  fileQueueEndpoint: tcp://localhost:44446

cache:
  cacheSize: 10000