zmq:
  senderEndpoint: tcp://localhost:44445
  receiverEndpoint: tcp://localhost:44444
  fileQueueEndpoint: tcp://localhost:44446

http:
  replayEndpoint: https://fumbbl.com/api/replay/get/%s/gz
  activateOutputLog: false
  outputPathTemplate: src/test/resources/baseline/output/%s.json
  activateInputLog: false
  inputPathTemplate: src/test/resources/baseline/input/%s.gz