/*
 * Decompiled with CFR 0_114.
 */
package com.balancedbytes.games.ffb.json;

import com.balancedbytes.games.ffb.BlockResultFactory;
import com.balancedbytes.games.ffb.CardEffectFactory;
import com.balancedbytes.games.ffb.CardFactory;
import com.balancedbytes.games.ffb.CardTypeFactory;
import com.balancedbytes.games.ffb.ClientModeFactory;
import com.balancedbytes.games.ffb.ClientStateIdFactory;
import com.balancedbytes.games.ffb.ConcedeGameStatusFactory;
import com.balancedbytes.games.ffb.DirectionFactory;
import com.balancedbytes.games.ffb.IEnumWithNameFactory;
import com.balancedbytes.games.ffb.InducementTypeFactory;
import com.balancedbytes.games.ffb.InjuryTypeFactory;
import com.balancedbytes.games.ffb.KickoffResultFactory;
import com.balancedbytes.games.ffb.LeaderStateFactory;
import com.balancedbytes.games.ffb.PassingDistanceFactory;
import com.balancedbytes.games.ffb.PlayerActionFactory;
import com.balancedbytes.games.ffb.PlayerChoiceModeFactory;
import com.balancedbytes.games.ffb.PlayerGenderFactory;
import com.balancedbytes.games.ffb.PlayerTypeFactory;
import com.balancedbytes.games.ffb.PushbackModeFactory;
import com.balancedbytes.games.ffb.ReRollSourceFactory;
import com.balancedbytes.games.ffb.ReRolledActionFactory;
import com.balancedbytes.games.ffb.SendToBoxReasonFactory;
import com.balancedbytes.games.ffb.SeriousInjuryFactory;
import com.balancedbytes.games.ffb.SkillFactory;
import com.balancedbytes.games.ffb.SkillUseFactory;
import com.balancedbytes.games.ffb.SoundIdFactory;
import com.balancedbytes.games.ffb.SpecialEffectFactory;
import com.balancedbytes.games.ffb.TeamStatusFactory;
import com.balancedbytes.games.ffb.TurnModeFactory;
import com.balancedbytes.games.ffb.WeatherFactory;
import com.balancedbytes.games.ffb.dialog.DialogIdFactory;
import com.balancedbytes.games.ffb.json.JsonArrayOption;
import com.balancedbytes.games.ffb.json.JsonBooleanArrayOption;
import com.balancedbytes.games.ffb.json.JsonBooleanOption;
import com.balancedbytes.games.ffb.json.JsonDateOption;
import com.balancedbytes.games.ffb.json.JsonEnumWithNameOption;
import com.balancedbytes.games.ffb.json.JsonFieldCoordinateArrayOption;
import com.balancedbytes.games.ffb.json.JsonFieldCoordinateOption;
import com.balancedbytes.games.ffb.json.JsonIntArrayOption;
import com.balancedbytes.games.ffb.json.JsonIntOption;
import com.balancedbytes.games.ffb.json.JsonLongOption;
import com.balancedbytes.games.ffb.json.JsonObjectOption;
import com.balancedbytes.games.ffb.json.JsonPlayerStateOption;
import com.balancedbytes.games.ffb.json.JsonStringArrayOption;
import com.balancedbytes.games.ffb.json.JsonStringOption;
import com.balancedbytes.games.ffb.json.JsonValueOption;
import com.balancedbytes.games.ffb.model.AnimationTypeFactory;
import com.balancedbytes.games.ffb.model.change.ModelChangeIdFactory;
import com.balancedbytes.games.ffb.net.NetCommandIdFactory;
import com.balancedbytes.games.ffb.net.ServerStatusFactory;
import com.balancedbytes.games.ffb.option.GameOptionIdFactory;
import com.balancedbytes.games.ffb.report.ReportIdFactory;

public interface IJsonOption {
    public static final JsonObjectOption ACTING_PLAYER = new JsonObjectOption("actingPlayer");
    public static final JsonStringOption ACTING_PLAYER_ID = new JsonStringOption("actingPlayerId");
    public static final JsonIntOption AGILITY = new JsonIntOption("agility");
    public static final JsonObjectOption ANIMATION = new JsonObjectOption("animation");
    public static final JsonEnumWithNameOption ANIMATION_TYPE = new JsonEnumWithNameOption("animationType", new AnimationTypeFactory());
    public static final JsonIntOption APOTHECARIES = new JsonIntOption("apothecaries");
    public static final JsonBooleanOption APOTHECARY = new JsonBooleanOption("apothecary");
    public static final JsonBooleanOption APOTHECARY_USED = new JsonBooleanOption("apothecaryUsed");
    public static final JsonBooleanOption ARMOR_BROKEN = new JsonBooleanOption("armorBroken");
    public static final JsonArrayOption ARMOR_MODIFIERS = new JsonArrayOption("armorModifiers");
    public static final JsonIntArrayOption ARMOR_ROLL = new JsonIntArrayOption("armorRoll");
    public static final JsonIntOption ARMOUR = new JsonIntOption("armour");
    public static final JsonIntOption ASSISTANT_COACHES = new JsonIntOption("assistantCoaches");
    public static final JsonStringOption ATTACKER_ID = new JsonStringOption("attackerId");
    public static final JsonIntOption AVAILABLE_CARDS = new JsonIntOption("availableCards");
    public static final JsonIntOption AVAILABLE_GOLD = new JsonIntOption("availableGold");
    public static final JsonBooleanOption AWAY_GAINS_RE_ROLL = new JsonBooleanOption("awayGainsReRoll");
    public static final JsonStringOption AWAY_TEXT = new JsonStringOption("awayText");
    public static final JsonIntOption BADLY_HURT_SUFFERED = new JsonIntOption("badlyHurtSuffered");
    public static final JsonFieldCoordinateOption BALL_COORDINATE = new JsonFieldCoordinateOption("ballCoordinate");
    public static final JsonFieldCoordinateOption BALL_COORDINATE_END = new JsonFieldCoordinateOption("ballCoordinateEnd");
    public static final JsonFieldCoordinateOption BALL_COORDINATE_WITH_KICK = new JsonFieldCoordinateOption("ballCoordinateWithKick");
    public static final JsonBooleanOption BALL_IN_PLAY = new JsonBooleanOption("ballInPlay");
    public static final JsonBooleanOption BALL_MOVING = new JsonBooleanOption("ballMoving");
    public static final JsonBooleanArrayOption BAN_ARRAY = new JsonBooleanArrayOption("banArray");
    public static final JsonStringOption BASE_ICON_PATH = new JsonStringOption("baseIconPath");
    public static final JsonBooleanOption BLITZ_USED = new JsonBooleanOption("blitzUsed");
    public static final JsonEnumWithNameOption BLOCK_RESULT = new JsonEnumWithNameOption("blockResult", new BlockResultFactory());
    public static final JsonIntArrayOption BLOCK_ROLL = new JsonIntArrayOption("blockRoll");
    public static final JsonIntOption BLOCKS = new JsonIntOption("blocks");
    public static final JsonArrayOption BLOODSPOT_ARRAY = new JsonArrayOption("bloodspotArray");
    public static final JsonIntOption BLOODWEISER_BABES = new JsonIntOption("bloodweiserBabes");
    public static final JsonBooleanOption BOMB = new JsonBooleanOption("bomb");
    public static final JsonFieldCoordinateOption BOMB_COORDINATE = new JsonFieldCoordinateOption("bombCoordinate");
    public static final JsonBooleanOption BOMB_MOVING = new JsonBooleanOption("bombMoving");
    public static final JsonFieldCoordinateOption BOTTOM_RIGHT = new JsonFieldCoordinateOption("bottomRight");
    public static final JsonEnumWithNameOption CARD = new JsonEnumWithNameOption("card", new CardFactory());
    public static final JsonStringArrayOption CARDS = new JsonStringArrayOption("cards");
    public static final JsonEnumWithNameOption CARD_EFFECT = new JsonEnumWithNameOption("cardEffect", new CardEffectFactory());
    public static final JsonStringArrayOption CARD_EFFECTS = new JsonStringArrayOption("cardEffects");
    public static final JsonStringArrayOption CARDS_ACTIVE = new JsonStringArrayOption("cardsActive");
    public static final JsonStringArrayOption CARDS_AVAILABLE = new JsonStringArrayOption("cardsAvailable");
    public static final JsonStringArrayOption CARDS_DEACTIVATED = new JsonStringArrayOption("cardsDeactivated");
    public static final JsonEnumWithNameOption CARD_TYPE = new JsonEnumWithNameOption("cardType", new CardTypeFactory());
    public static final JsonIntOption CASUALTIES = new JsonIntOption("casualties");
    public static final JsonIntArrayOption CASUALTY_ROLL = new JsonIntArrayOption("casualtyRoll");
    public static final JsonIntArrayOption CASUALTY_ROLL_DECAY = new JsonIntArrayOption("casualtyRollDecay");
    public static final JsonStringOption CATCHER_ID = new JsonStringOption("catcherId");
    public static final JsonStringOption CHALLENGE = new JsonStringOption("challenge");
    public static final JsonIntOption CHEERLEADERS = new JsonIntOption("cheerleaders");
    public static final JsonBooleanOption CHOICE_FOLLOWUP = new JsonBooleanOption("choiceFollowup");
    public static final JsonBooleanOption CHOICE_HEADS = new JsonBooleanOption("choiceHeads");
    public static final JsonBooleanOption CHOICE_RECEIVE = new JsonBooleanOption("choiceReceive");
    public static final JsonStringOption CHOOSING_TEAM_ID = new JsonStringOption("choosingTeamId");
    public static final JsonEnumWithNameOption CLIENT_MODE = new JsonEnumWithNameOption("clientMode", new ClientModeFactory());
    public static final JsonStringArrayOption CLIENT_PROPERTY_NAMES = new JsonStringArrayOption("clientPropertyNames");
    public static final JsonStringArrayOption CLIENT_PROPERTY_VALUES = new JsonStringArrayOption("clientPropertyValues");
    public static final JsonEnumWithNameOption CLIENT_STATE_ID = new JsonEnumWithNameOption("clientStateId", new ClientStateIdFactory());
    public static final JsonStringOption CLIENT_VERSION = new JsonStringOption("clientVersion");
    public static final JsonStringOption COACH = new JsonStringOption("coach");
    public static final JsonBooleanOption COIN_CHOICE_HEADS = new JsonBooleanOption("coinChoiceHeads");
    public static final JsonBooleanOption COIN_THROW_HEADS = new JsonBooleanOption("coinThrowHeads");
    public static final JsonArrayOption COMMAND_ARRAY = new JsonArrayOption("commandArray");
    public static final JsonIntOption COMMAND_NR = new JsonIntOption("commandNr");
    public static final JsonIntOption COMPLETIONS = new JsonIntOption("completions");
    public static final JsonEnumWithNameOption CONCEDE_GAME_STATUS = new JsonEnumWithNameOption("concedeGameStatus", new ConcedeGameStatusFactory());
    public static final JsonBooleanOption CONCEDED = new JsonBooleanOption("conceded");
    public static final JsonStringOption CONCEDING_TEAM_ID = new JsonStringOption("concedingTeamId");
    public static final JsonBooleanOption CONCESSION_POSSIBLE = new JsonBooleanOption("concessionPossible");
    public static final JsonEnumWithNameOption CONFUSION_SKILL = new JsonEnumWithNameOption("confusionSkill", new SkillFactory());
    public static final JsonFieldCoordinateOption COORDINATE = new JsonFieldCoordinateOption("coordinate");
    public static final JsonFieldCoordinateOption COORDINATE_FROM = new JsonFieldCoordinateOption("coordinateFrom");
    public static final JsonFieldCoordinateArrayOption COORDINATES_TO = new JsonFieldCoordinateArrayOption("coordinatesTo");
    public static final JsonIntOption COST = new JsonIntOption("cost");
    public static final JsonIntOption CURRENT_MOVE = new JsonIntOption("currentMove");
    public static final JsonIntOption CURRENT_SPPS = new JsonIntOption("currentSpps");
    public static final JsonBooleanOption DEFECTING = new JsonBooleanOption("defecting");
    public static final JsonBooleanArrayOption DEFECTING_ARRAY = new JsonBooleanArrayOption("defectingArray");
    public static final JsonEnumWithNameOption DEFENDER_ACTION = new JsonEnumWithNameOption("defenderAction", new PlayerActionFactory());
    public static final JsonStringOption DEFENDER_ID = new JsonStringOption("defenderId");
    public static final JsonStringArrayOption DESCRIPTIONS = new JsonStringArrayOption("descriptions");
    public static final JsonEnumWithNameOption DIALOG_ID = new JsonEnumWithNameOption("dialogId", new DialogIdFactory());
    public static final JsonObjectOption DIALOG_PARAMETER = new JsonObjectOption("dialogParameter");
    public static final JsonArrayOption DICE_DECORATION_ARRAY = new JsonArrayOption("diceDecorationArray");
    public static final JsonIntOption DICE_INDEX = new JsonIntOption("diceIndex");
    public static final JsonEnumWithNameOption DIRECTION = new JsonEnumWithNameOption("direction", new DirectionFactory());
    public static final JsonArrayOption DIRECTION_ARRAY = new JsonArrayOption("directionArray");
    public static final JsonIntOption DIRECTION_ROLL = new JsonIntOption("directionRoll");
    public static final JsonStringOption DISPLAY_NAME = new JsonStringOption("displayName");
    public static final JsonIntArrayOption DISTANCE_ROLL = new JsonIntArrayOption("distanceRoll");
    public static final JsonStringOption DIVISION = new JsonStringOption("division");
    public static final JsonBooleanOption DODGING = new JsonBooleanOption("dodging");
    public static final JsonFieldCoordinateOption END_COORDINATE = new JsonFieldCoordinateOption("endCoordinate");
    public static final JsonIntOption ENTROPY = new JsonIntOption("entropy");
    public static final JsonBooleanOption EXHAUSTED = new JsonBooleanOption("exhausted");
    public static final JsonIntOption FAME = new JsonIntOption("fame");
    public static final JsonIntOption FAME_AWAY = new JsonIntOption("fameAway");
    public static final JsonIntOption FAME_HOME = new JsonIntOption("fameHome");
    public static final JsonIntOption FAN_FACTOR = new JsonIntOption("fanFactor");
    public static final JsonIntOption FAN_FACTOR_MODIFIER = new JsonIntOption("fanFactorModifier");
    public static final JsonIntOption FAN_FACTOR_MODIFIER_AWAY = new JsonIntOption("fanFactorModifierAway");
    public static final JsonIntOption FAN_FACTOR_MODIFIER_HOME = new JsonIntOption("fanFactorModifierHome");
    public static final JsonIntArrayOption FAN_FACTOR_ROLL_AWAY = new JsonIntArrayOption("fanFactorRollAway");
    public static final JsonIntArrayOption FAN_FACTOR_ROLL_HOME = new JsonIntArrayOption("fanFactorRollHome");
    public static final JsonArrayOption FIELD_MARKER_ARRAY = new JsonArrayOption("fieldMarkerArray");
    public static final JsonObjectOption FIELD_MODEL = new JsonObjectOption("fieldModel");
    public static final JsonDateOption FINISHED = new JsonDateOption("finished");
    public static final JsonBooleanOption FIRST_TURN_AFTER_KICKOFF = new JsonBooleanOption("firstTurnAfterKickoff");
    public static final JsonBooleanOption FOUL_USED = new JsonBooleanOption("foulUsed");
    public static final JsonBooleanOption FOULING_PLAYER_BANNED = new JsonBooleanOption("foulingPlayerBanned");
    public static final JsonIntOption FOULS = new JsonIntOption("fouls");
    public static final JsonBooleanOption FUMBLE = new JsonBooleanOption("fumble");
    public static final JsonObjectOption GAME = new JsonObjectOption("game");
    public static final JsonLongOption GAME_ID = new JsonLongOption("gameId");
    public static final JsonObjectOption GAME_LIST = new JsonObjectOption("gameList");
    public static final JsonArrayOption GAME_LIST_ENTRIES = new JsonArrayOption("gameListEntries");
    public static final JsonStringOption GAME_NAME = new JsonStringOption("gameName");
    public static final JsonArrayOption GAME_OPTION_ARRAY = new JsonArrayOption("gameOptionArray");
    public static final JsonEnumWithNameOption GAME_OPTION_ID = new JsonEnumWithNameOption("gameOptionId", new GameOptionIdFactory());
    public static final JsonStringOption GAME_OPTION_VALUE = new JsonStringOption("gameOptionValue");
    public static final JsonObjectOption GAME_OPTIONS = new JsonObjectOption("gameOptions");
    public static final JsonObjectOption GAME_RESULT = new JsonObjectOption("gameResult");
    public static final JsonLongOption GAME_TIME = new JsonLongOption("gameTime");
    public static final JsonBooleanOption GOING_FOR_IT = new JsonBooleanOption("goingForIt");
    public static final JsonIntOption GOLD = new JsonIntOption("gold");
    public static final JsonBooleanOption GUST_OF_WIND = new JsonBooleanOption("gustOfWind");
    public static final JsonBooleanOption HAIL_MARY_PASS = new JsonBooleanOption("hailMaryPass");
    public static final JsonIntOption HALF = new JsonIntOption("half");
    public static final JsonBooleanOption HAND_OVER_USED = new JsonBooleanOption("handOverUsed");
    public static final JsonBooleanOption HAS_BLOCKED = new JsonBooleanOption("hasBlocked");
    public static final JsonBooleanOption HAS_ENTROPY = new JsonBooleanOption("hasEntropy");
    public static final JsonBooleanOption HAS_FED = new JsonBooleanOption("hasFed");
    public static final JsonBooleanOption HAS_FOULED = new JsonBooleanOption("hasFouled");
    public static final JsonBooleanOption HAS_MOVED = new JsonBooleanOption("hasMoved");
    public static final JsonBooleanOption HAS_PASSED = new JsonBooleanOption("hasPassed");
    public static final JsonBooleanOption HAS_USED_SECRET_WEAPON = new JsonBooleanOption("hasUsedSecretWeapon");
    public static final JsonArrayOption HEAT_EXHAUSTION_ARRAY = new JsonArrayOption("heatExhaustionArray");
    public static final JsonBooleanOption HOME_CHOICE = new JsonBooleanOption("homeChoice");
    public static final JsonBooleanOption HOME_DATA = new JsonBooleanOption("homeData");
    public static final JsonBooleanOption HOME_FIRST_OFFENSE = new JsonBooleanOption("homeFirstOffense");
    public static final JsonBooleanOption HOME_GAINS_RE_ROLL = new JsonBooleanOption("homeGainsReRoll");
    public static final JsonBooleanOption HOME_PLAYING = new JsonBooleanOption("homePlaying");
    public static final JsonBooleanOption HOME_TEAM = new JsonBooleanOption("homeTeam");
    public static final JsonStringOption HOME_TEXT = new JsonStringOption("homeText");
    public static final JsonStringArrayOption ICON_URLS_AWAY_MOVING = new JsonStringArrayOption("iconUrlsAwayMoving");
    public static final JsonStringArrayOption ICON_URLS_AWAY_STANDING = new JsonStringArrayOption("iconUrlsAwayStanding");
    public static final JsonStringArrayOption ICON_URLS_HOME_MOVING = new JsonStringArrayOption("iconUrlsHomeMoving");
    public static final JsonStringArrayOption ICON_URLS_HOME_STANDING = new JsonStringArrayOption("iconUrlsHomeStanding");
    public static final JsonArrayOption INDUCEMENT_ARRAY = new JsonArrayOption("inducementArray");
    public static final JsonObjectOption INDUCEMENT_SET = new JsonObjectOption("inducementSet");
    public static final JsonEnumWithNameOption INDUCEMENT_TYPE = new JsonEnumWithNameOption("inducementType", new InducementTypeFactory());
    public static final JsonStringArrayOption INDUCEMENT_TYPE_ARRAY = new JsonStringArrayOption("inducementTypeArray");
    public static final JsonPlayerStateOption INJURY = new JsonPlayerStateOption("injury");
    public static final JsonPlayerStateOption INJURY_DECAY = new JsonPlayerStateOption("injuryDecay");
    public static final JsonArrayOption INJURY_MODIFIERS = new JsonArrayOption("injuryModifiers");
    public static final JsonIntArrayOption INJURY_ROLL = new JsonIntArrayOption("injuryRoll");
    public static final JsonEnumWithNameOption INJURY_TYPE = new JsonEnumWithNameOption("injuryType", new InjuryTypeFactory());
    public static final JsonIntOption INTERCEPTIONS = new JsonIntOption("interceptions");
    public static final JsonFieldCoordinateOption INTERCEPTOR_COORDINATE = new JsonFieldCoordinateOption("interceptorCoordinate");
    public static final JsonStringOption INTERCEPTOR_ID = new JsonStringOption("interceptorId");
    public static final JsonEnumWithNameOption KICKOFF_RESULT = new JsonEnumWithNameOption("kickoffResult", new KickoffResultFactory());
    public static final JsonIntArrayOption KICKOFF_ROLL = new JsonIntArrayOption("kickoffRoll");
    public static final JsonArrayOption KNOCKOUT_RECOVERY_ARRAY = new JsonArrayOption("knockoutRecoveryArray");
    public static final JsonArrayOption LASTING_INJURIES = new JsonArrayOption("lastingInjuries");
    public static final JsonEnumWithNameOption LEADER_STATE = new JsonEnumWithNameOption("leaderState", new LeaderStateFactory());
    public static final JsonBooleanOption LEAPING = new JsonBooleanOption("leaping");
    public static final JsonBooleanOption LOAD_DIALOG = new JsonBooleanOption("loadDialog");
    public static final JsonBooleanOption LOCKED = new JsonBooleanOption("locked");
    public static final JsonStringOption LOGO_URL = new JsonStringOption("logoUrl");
    public static final JsonIntArrayOption MASTER_CHEF_ROLL = new JsonIntArrayOption("masterChefRoll");
    public static final JsonIntOption MAX_NR_OF_BRIBES = new JsonIntOption("maxNrOfBribes");
    public static final JsonIntOption MAX_RE_ROLLS = new JsonIntOption("maxReRolls");
    public static final JsonIntOption MAX_SELECTS = new JsonIntOption("maxSelects");
    public static final JsonStringArrayOption MERCENARY_POSTION_IDS = new JsonStringArrayOption("mercenaryPositionIds");
    public static final JsonStringArrayOption MERCENARY_SKILLS = new JsonStringArrayOption("mercenarySkills");
    public static final JsonStringOption MESSAGE = new JsonStringOption("message");
    public static final JsonStringArrayOption MESSAGE_ARRAY = new JsonStringArrayOption("messageArray");
    public static final JsonIntOption MINIMUM_ROLL = new JsonIntOption("minimumRoll");
    public static final JsonIntOption MINIMUM_ROLL_DODGE = new JsonIntOption("minimumRollDodge");
    public static final JsonIntOption MINIMUM_ROLL_GFI = new JsonIntOption("minimumRollGfi");
    public static final JsonArrayOption MODEL_CHANGE_ARRAY = new JsonArrayOption("modelChangeArray");
    public static final JsonEnumWithNameOption MODEL_CHANGE_ID = new JsonEnumWithNameOption("modelChangeId", new ModelChangeIdFactory());
    public static final JsonStringOption MODEL_CHANGE_KEY = new JsonStringOption("modelChangeKey");
    public static final JsonObjectOption MODEL_CHANGE_LIST = new JsonObjectOption("modelChangeList");
    public static final JsonValueOption MODEL_CHANGE_VALUE = new JsonValueOption("modelChangeValue");
    public static final JsonArrayOption MOVE_SQUARE_ARRAY = new JsonArrayOption("moveSquareArray");
    public static final JsonIntOption MOVEMENT = new JsonIntOption("movement");
    public static final JsonStringOption NAME = new JsonStringOption("name");
    public static final JsonBooleanOption NECROMANCER = new JsonBooleanOption("necromancer");
    public static final JsonEnumWithNameOption NET_COMMAND_ID = new JsonEnumWithNameOption("netCommandId", new NetCommandIdFactory());
    public static final JsonArrayOption NR_OF_CARDS_PER_TYPE = new JsonArrayOption("nrOfCardsPerType");
    public static final JsonIntOption NR_OF_CARDS = new JsonIntOption("nrOfCards");
    public static final JsonIntOption NR_OF_DICE = new JsonIntOption("nrOfDice");
    public static final JsonIntOption NR_OF_ICONS = new JsonIntOption("nrOfIcons");
    public static final JsonIntOption NR_OF_INDUCEMENTS = new JsonIntOption("nrOfInducements");
    public static final JsonIntOption NR_OF_MERCENARIES = new JsonIntOption("nrOfMercenaries");
    public static final JsonIntOption NR_OF_SLOTS = new JsonIntOption("nrOfSlots");
    public static final JsonIntOption NR_OF_STARS = new JsonIntOption("nrOfStars");
    public static final JsonIntOption NUMBER = new JsonIntOption("number");
    public static final JsonBooleanOption NURGLES_ROT = new JsonBooleanOption("nurglesRot");
    public static final JsonIntOption OLD_ROLL = new JsonIntOption("oldRoll");
    public static final JsonIntOption OPPONENT_TEAM_VALUE = new JsonIntOption("opponentTeamValue");
    public static final JsonBooleanOption PASS_BLOCK_AVAILABLE = new JsonBooleanOption("passBlockAvailable");
    public static final JsonFieldCoordinateOption PASS_COORDINATE = new JsonFieldCoordinateOption("passCoordinate");
    public static final JsonBooleanOption PASS_USED = new JsonBooleanOption("passUsed");
    public static final JsonEnumWithNameOption PASSING_DISTANCE = new JsonEnumWithNameOption("passingDistance", new PassingDistanceFactory());
    public static final JsonStringOption PASSWORD = new JsonStringOption("password");
    public static final JsonIntOption PASSING = new JsonIntOption("passing");
    public static final JsonIntOption PETTY_CASH = new JsonIntOption("pettyCash");
    public static final JsonIntOption PETTY_CASH_TRANSFERRED = new JsonIntOption("pettyCashTransferred");
    public static final JsonIntOption PETTY_CASH_USED = new JsonIntOption("pettyCashUsed");
    public static final JsonObjectOption PLAYER = new JsonObjectOption("player");
    public static final JsonEnumWithNameOption PLAYER_ACTION = new JsonEnumWithNameOption("playerAction", new PlayerActionFactory());
    public static final JsonArrayOption PLAYER_ARRAY = new JsonArrayOption("playerArray");
    public static final JsonIntOption PLAYER_AWARDS = new JsonIntOption("playerAwards");
    public static final JsonEnumWithNameOption PLAYER_CHOICE_MODE = new JsonEnumWithNameOption("playerChoiceMode", new PlayerChoiceModeFactory());
    public static final JsonFieldCoordinateOption PLAYER_COORDINATE = new JsonFieldCoordinateOption("playerCoordinate");
    public static final JsonFieldCoordinateArrayOption PLAYER_COORDINATES = new JsonFieldCoordinateArrayOption("playerCoordinates");
    public static final JsonArrayOption PLAYER_DATA_ARRAY = new JsonArrayOption("playerDataArray");
    public static final JsonEnumWithNameOption PLAYER_GENDER = new JsonEnumWithNameOption("playerGender", new PlayerGenderFactory());
    public static final JsonStringOption PLAYER_ID = new JsonStringOption("playerId");
    public static final JsonStringOption PLAYER_ID_TOUCHDOWN = new JsonStringOption("playerIdTouchdown");
    public static final JsonStringArrayOption PLAYER_IDS = new JsonStringArrayOption("playerIds");
    public static final JsonStringArrayOption PLAYER_IDS_AWAY = new JsonStringArrayOption("playerIdsAway");
    public static final JsonStringArrayOption PLAYER_IDS_HIT = new JsonStringArrayOption("playerIdsHit");
    public static final JsonStringArrayOption PLAYER_IDS_HOME = new JsonStringArrayOption("playerIdsHome");
    public static final JsonArrayOption PLAYER_MARKER_ARRAY = new JsonArrayOption("playerMarkerArray");
    public static final JsonStringOption PLAYER_NAME = new JsonStringOption("playerName");
    public static final JsonStringArrayOption PLAYER_NAMES = new JsonStringArrayOption("playerNames");
    public static final JsonIntOption PLAYER_NR = new JsonIntOption("playerNr");
    public static final JsonIntArrayOption PLAYER_NUMBERS = new JsonIntArrayOption("playerNumbers");
    public static final JsonArrayOption PLAYER_POSITIONS = new JsonArrayOption("playerPositions");
    public static final JsonArrayOption PLAYER_RESULTS = new JsonArrayOption("playerResults");
    public static final JsonPlayerStateOption PLAYER_STATE = new JsonPlayerStateOption("playerState");
    public static final JsonPlayerStateOption PLAYER_STATE_NEW = new JsonPlayerStateOption("playerStateNew");
    public static final JsonPlayerStateOption PLAYER_STATE_OLD = new JsonPlayerStateOption("playerStateOld");
    public static final JsonEnumWithNameOption PLAYER_TYPE = new JsonEnumWithNameOption("playerType", new PlayerTypeFactory());
    public static final JsonBooleanArrayOption PLAYERS_AFFECTED_AWAY = new JsonBooleanArrayOption("playersAffectedAway");
    public static final JsonBooleanArrayOption PLAYERS_AFFECTED_HOME = new JsonBooleanArrayOption("playersAffectedHome");
    public static final JsonArrayOption POSITION_ARRAY = new JsonArrayOption("positionArray");
    public static final JsonIntOption POSITION_ICON_INDEX = new JsonIntOption("positionIconIndex");
    public static final JsonStringOption POSITION_ID = new JsonStringOption("positionId");
    public static final JsonStringArrayOption POSITION_IDS = new JsonStringArrayOption("positionIds");
    public static final JsonStringOption POSITION_NAME = new JsonStringOption("positionName");
    public static final JsonBooleanOption PRO_RE_ROLL_OPTION = new JsonBooleanOption("proReRollOption");
    public static final JsonObjectOption PUSHBACK = new JsonObjectOption("pushback");
    public static final JsonEnumWithNameOption PUSHBACK_MODE = new JsonEnumWithNameOption("pushbackMode", new PushbackModeFactory());
    public static final JsonArrayOption PUSHBACK_SQUARE_ARRAY = new JsonArrayOption("pushbackSquareArray");
    public static final JsonIntOption QUANTITY = new JsonIntOption("quantity");
    public static final JsonStringOption RACE = new JsonStringOption("race");
    public static final JsonIntOption RAISED_DEAD = new JsonIntOption("raisedDead");
    public static final JsonStringOption RAISED_POSITION_ID = new JsonStringOption("raisedPositionId");
    public static final JsonBooleanOption RECEIVE_CHOICE = new JsonBooleanOption("receiveChoice");
    public static final JsonBooleanOption RECOVERING = new JsonBooleanOption("recovering");
    public static final JsonEnumWithNameOption RECOVERING_INJURY = new JsonEnumWithNameOption("recoveringInjury", new SeriousInjuryFactory());
    public static final JsonIntOption REPLAY_TO_COMMAND_NR = new JsonIntOption("replayToCommandNr");
    public static final JsonEnumWithNameOption REPORT_ID = new JsonEnumWithNameOption("reportId", new ReportIdFactory());
    public static final JsonObjectOption REPORT_LIST = new JsonObjectOption("reportList");
    public static final JsonArrayOption REPORTS = new JsonArrayOption("reports");
    public static final JsonBooleanOption RE_ROLLED = new JsonBooleanOption("reRolled");
    public static final JsonEnumWithNameOption RE_ROLLED_ACTION = new JsonEnumWithNameOption("reRolledAction", new ReRolledActionFactory());
    public static final JsonIntOption RE_ROLL_COST = new JsonIntOption("reRollCost");
    public static final JsonBooleanOption RE_ROLL_INJURY = new JsonBooleanOption("reRollInjury");
    public static final JsonEnumWithNameOption RE_ROLL_SOURCE = new JsonEnumWithNameOption("reRollSource", new ReRollSourceFactory());
    public static final JsonBooleanOption RE_ROLL_USED = new JsonBooleanOption("reRollUsed");
    public static final JsonIntOption RE_ROLLS = new JsonIntOption("reRolls");
    public static final JsonIntOption RE_ROLLS_LEFT_AWAY = new JsonIntOption("reRollsLeftAway");
    public static final JsonIntOption RE_ROLLS_LEFT_HOME = new JsonIntOption("reRollsLeftHome");
    public static final JsonIntOption RE_ROLLS_STOLEN = new JsonIntOption("reRollsStolen");
    public static final JsonIntOption RIP_SUFFERED = new JsonIntOption("ripSuffered");
    public static final JsonIntOption ROLL = new JsonIntOption("roll");
    public static final JsonIntOption ROLL_SCATTER_DIRECTION = new JsonIntOption("rollScatterDirection");
    public static final JsonIntOption ROLL_SCATTER_DISTANCE = new JsonIntOption("rollScatterDistance");
    public static final JsonIntOption ROLL_AWAY = new JsonIntOption("rollAway");
    public static final JsonIntOption ROLL_HOME = new JsonIntOption("rollHome");
    public static final JsonArrayOption ROLL_MODIFIERS = new JsonArrayOption("rollModifiers");
    public static final JsonIntArrayOption ROLLS = new JsonIntArrayOption("rolls");
    public static final JsonIntArrayOption ROLLS_AWAY = new JsonIntArrayOption("rollsAway");
    public static final JsonIntArrayOption ROLLS_HOME = new JsonIntArrayOption("rollsHome");
    public static final JsonObjectOption ROSTER = new JsonObjectOption("roster");
    public static final JsonStringOption ROSTER_ID = new JsonStringOption("rosterId");
    public static final JsonStringOption ROSTER_NAME = new JsonStringOption("rosterName");
    public static final JsonIntOption RUSHING = new JsonIntOption("rushing");
    public static final JsonBooleanOption SAFE_THROW_HOLD = new JsonBooleanOption("safeThrowHold");
    public static final JsonEnumWithNameOption SCATTER_DIRECTION = new JsonEnumWithNameOption("scatterDirection", new DirectionFactory());
    public static final JsonDateOption SCHEDULED = new JsonDateOption("scheduled");
    public static final JsonIntOption SCORE = new JsonIntOption("score");
    public static final JsonBooleanOption SELECTED = new JsonBooleanOption("selected");
    public static final JsonStringOption SEND_TO_BOX_BY_PLAYER_ID = new JsonStringOption("sendToBoxByPlayerId");
    public static final JsonIntOption SEND_TO_BOX_HALF = new JsonIntOption("sendToBoxHalf");
    public static final JsonEnumWithNameOption SEND_TO_BOX_REASON = new JsonEnumWithNameOption("sendToBoxReason", new SendToBoxReasonFactory());
    public static final JsonIntOption SEND_TO_BOX_TURN = new JsonIntOption("sendToBoxTurn");
    public static final JsonEnumWithNameOption SERIOUS_INJURY = new JsonEnumWithNameOption("seriousInjury", new SeriousInjuryFactory());
    public static final JsonEnumWithNameOption SERIOUS_INJURY_DECAY = new JsonEnumWithNameOption("seriousInjuryDecay", new SeriousInjuryFactory());
    public static final JsonEnumWithNameOption SERIOUS_INJURY_NEW = new JsonEnumWithNameOption("seriousInjuryNew", new SeriousInjuryFactory());
    public static final JsonEnumWithNameOption SERIOUS_INJURY_OLD = new JsonEnumWithNameOption("seriousInjuryOld", new SeriousInjuryFactory());
    public static final JsonIntOption SERIOUS_INJURY_SUFFERED = new JsonIntOption("seriousInjurySuffered");
    public static final JsonEnumWithNameOption SERVER_STATUS = new JsonEnumWithNameOption("serverStatus", new ServerStatusFactory());
    public static final JsonStringOption SERVER_VERSION = new JsonStringOption("serverVersion");
    public static final JsonStringArrayOption SETTING_NAMES = new JsonStringArrayOption("settingNames");
    public static final JsonStringArrayOption SETTING_VALUES = new JsonStringArrayOption("settingValues");
    public static final JsonStringArrayOption SETUP_ERRORS = new JsonStringArrayOption("setupErrors");
    public static final JsonStringOption SETUP_NAME = new JsonStringOption("setupName");
    public static final JsonStringArrayOption SETUP_NAMES = new JsonStringArrayOption("setupNames");
    public static final JsonBooleanOption SETUP_OFFENSE = new JsonBooleanOption("setupOffense");
    public static final JsonStringOption SHORTHAND = new JsonStringOption("shorthand");
    public static final JsonEnumWithNameOption SKILL = new JsonEnumWithNameOption("skill", new SkillFactory());
    public static final JsonArrayOption SKILL_ARRAY = new JsonArrayOption("skillArray");
    public static final JsonArrayOption SKILL_CATEGORIES_DOUBLE = new JsonArrayOption("skillCategoriesDouble");
    public static final JsonArrayOption SKILL_CATEGORIES_NORMAL = new JsonArrayOption("skillCategoriesNormal");
    public static final JsonEnumWithNameOption SKILL_USE = new JsonEnumWithNameOption("skillUse", new SkillUseFactory());
    public static final JsonIntArrayOption SKILL_VALUES = new JsonIntArrayOption("skillValues");
    public static final JsonBooleanOption SKILL_USED = new JsonBooleanOption("skillUsed");
    public static final JsonIntArrayOption SLOTS = new JsonIntArrayOption("slots");
    public static final JsonEnumWithNameOption SOUND = new JsonEnumWithNameOption("sound", new SoundIdFactory());
    public static final JsonEnumWithNameOption SPECIAL_EFFECT = new JsonEnumWithNameOption("specialEffect", new SpecialEffectFactory());
    public static final JsonIntArrayOption SPECTATOR_ROLL_AWAY = new JsonIntArrayOption("spectatorRollAway");
    public static final JsonIntArrayOption SPECTATOR_ROLL_HOME = new JsonIntArrayOption("spectatorRollHome");
    public static final JsonIntOption SPECTATORS = new JsonIntOption("spectators");
    public static final JsonIntOption SPECTATORS_AWAY = new JsonIntOption("spectatorsAway");
    public static final JsonIntOption SPECTATORS_HOME = new JsonIntOption("spectatorsHome");
    public static final JsonIntOption SPIRALLING_EXPENSES = new JsonIntOption("spirallingExpenses");
    public static final JsonBooleanOption STANDING_UP = new JsonBooleanOption("standingUp");
    public static final JsonStringOption STAR_PLAYER_NAME = new JsonStringOption("starPlayerName");
    public static final JsonStringArrayOption STAR_PLAYER_POSTION_IDS = new JsonStringArrayOption("starPlayerPositionIds");
    public static final JsonFieldCoordinateOption START_COORDINATE = new JsonFieldCoordinateOption("startCoordinate");
    public static final JsonDateOption STARTED = new JsonDateOption("started");
    public static final JsonIntOption STRENGTH = new JsonIntOption("strength");
    public static final JsonBooleanOption SUCCESSFUL = new JsonBooleanOption("successful");
    public static final JsonBooleanOption SUFFERING_ANIMOSITY = new JsonBooleanOption("sufferingAnimosity");
    public static final JsonBooleanOption SUFFERING_BLOODLUST = new JsonBooleanOption("sufferingBloodlust");
    public static final JsonStringOption TALK = new JsonStringOption("talk");
    public static final JsonStringArrayOption TALKS = new JsonStringArrayOption("talks");
    public static final JsonFieldCoordinateOption TARGET_COORDINATE = new JsonFieldCoordinateOption("targetCoordinate");
    public static final JsonObjectOption TEAM_AWAY = new JsonObjectOption("teamAway");
    public static final JsonStringOption TEAM_AWAY_COACH = new JsonStringOption("teamAwayCoach");
    public static final JsonStringOption TEAM_AWAY_ID = new JsonStringOption("teamAwayId");
    public static final JsonStringOption TEAM_AWAY_NAME = new JsonStringOption("teamAwayName");
    public static final JsonObjectOption TEAM_HOME = new JsonObjectOption("teamHome");
    public static final JsonStringOption TEAM_HOME_COACH = new JsonStringOption("teamHomeCoach");
    public static final JsonStringOption TEAM_HOME_ID = new JsonStringOption("teamHomeId");
    public static final JsonStringOption TEAM_HOME_NAME = new JsonStringOption("teamHomeName");
    public static final JsonStringOption TEAM_ID = new JsonStringOption("teamId");
    public static final JsonObjectOption TEAM_LIST = new JsonObjectOption("teamList");
    public static final JsonArrayOption TEAM_LIST_ENTRIES = new JsonArrayOption("teamListEntries");
    public static final JsonStringOption TEAM_NAME = new JsonStringOption("teamName");
    public static final JsonBooleanOption TEAM_RE_ROLL_OPTION = new JsonBooleanOption("teamReRollOption");
    public static final JsonObjectOption TEAM_RESULT_AWAY = new JsonObjectOption("teamResultAway");
    public static final JsonObjectOption TEAM_RESULT_HOME = new JsonObjectOption("teamResultHome");
    public static final JsonEnumWithNameOption TEAM_STATUS = new JsonEnumWithNameOption("teamStatus", new TeamStatusFactory());
    public static final JsonIntOption TEAM_VALUE = new JsonIntOption("teamValue");
    public static final JsonStringOption TEAM_WITH_POSITION_ID = new JsonStringOption("teamWithPositionId");
    public static final JsonIntArrayOption TENTACLE_ROLL = new JsonIntArrayOption("tentacleRoll");
    public static final JsonBooleanOption TESTING = new JsonBooleanOption("testing");
    public static final JsonStringOption TEXT = new JsonStringOption("text");
    public static final JsonBooleanOption THRALL = new JsonBooleanOption("thrall");
    public static final JsonEnumWithNameOption THROWER_ACTION = new JsonEnumWithNameOption("throwerAction", new PlayerActionFactory());
    public static final JsonStringOption THROWER_ID = new JsonStringOption("throwerId");
    public static final JsonStringOption THROWN_PLAYER_ID = new JsonStringOption("thrownPlayerId");
    public static final JsonBooleanOption THROW_TEAM_MATE = new JsonBooleanOption("throwTeamMate");
    public static final JsonBooleanOption TIMEOUT_ENFORCED = new JsonBooleanOption("timeoutEnforced");
    public static final JsonBooleanOption TIMEOUT_POSSIBLE = new JsonBooleanOption("timeoutPossible");
    public static final JsonLongOption TIMESTAMP = new JsonLongOption("timestamp");
    public static final JsonFieldCoordinateOption TOP_LEFT = new JsonFieldCoordinateOption("topLeft");
    public static final JsonIntOption TOTAL_NR_OF_COMMANDS = new JsonIntOption("totalNrOfCommands");
    public static final JsonIntOption TOUCHDOWNS = new JsonIntOption("touchdowns");
    public static final JsonArrayOption TRACK_NUMBER_ARRAY = new JsonArrayOption("trackNumberArray");
    public static final JsonIntOption TREASURY = new JsonIntOption("treasury");
    public static final JsonObjectOption TURN_DATA_AWAY = new JsonObjectOption("turnDataAway");
    public static final JsonObjectOption TURN_DATA_HOME = new JsonObjectOption("turnDataHome");
    public static final JsonEnumWithNameOption TURN_MODE = new JsonEnumWithNameOption("turnMode", new TurnModeFactory());
    public static final JsonIntOption TURN_MODIFIER = new JsonIntOption("turnModifier");
    public static final JsonIntOption TURN_NR = new JsonIntOption("turnNr");
    public static final JsonBooleanOption TURN_STARTED = new JsonBooleanOption("turnStarted");
    public static final JsonLongOption TURN_TIME = new JsonLongOption("turnTime");
    public static final JsonIntOption TURNS_PLAYED = new JsonIntOption("turnsPlayed");
    public static final JsonBooleanOption UNDEAD = new JsonBooleanOption("undead");
    public static final JsonStringOption UPLOAD_STATUS = new JsonStringOption("uploadStatus");
    public static final JsonStringOption URL_ICON_SET = new JsonStringOption("urlIconSet");
    public static final JsonStringOption URL_PORTRAIT = new JsonStringOption("urlPortrait");
    public static final JsonArrayOption USED_SKILLS = new JsonArrayOption("usedSkills");
    public static final JsonStringArrayOption USER_SETTING_NAMES = new JsonStringArrayOption("userSettingNames");
    public static final JsonStringArrayOption USER_SETTING_VALUES = new JsonStringArrayOption("userSettingValues");
    public static final JsonBooleanOption USED = new JsonBooleanOption("used");
    public static final JsonIntOption USES = new JsonIntOption("uses");
    public static final JsonBooleanOption USING_STAB = new JsonBooleanOption("usingStab");
    public static final JsonIntOption VALUE = new JsonIntOption("value");
    public static final JsonStringOption VICTIM_ID = new JsonStringOption("victimId");
    public static final JsonBooleanOption WAITING_FOR_OPPONENT = new JsonBooleanOption("waitingForOpponent");
    public static final JsonEnumWithNameOption WEATHER = new JsonEnumWithNameOption("weather", new WeatherFactory());
    public static final JsonIntArrayOption WEATHER_ROLL = new JsonIntArrayOption("weatherRoll");
    public static final JsonIntOption WINNINGS = new JsonIntOption("winnings");
    public static final JsonIntOption WINNINGS_AWAY = new JsonIntOption("winningsAway");
    public static final JsonIntOption WINNINGS_HOME = new JsonIntOption("winningsHome");
    public static final JsonIntOption WINNINGS_ROLL_AWAY = new JsonIntOption("winningsRollAway");
    public static final JsonIntOption WINNINGS_ROLL_HOME = new JsonIntOption("winningsRollHome");
    public static final JsonBooleanOption WITH_BALL = new JsonBooleanOption("withBall");
    public static final JsonEnumWithNameOption WIZARD_SPELL = new JsonEnumWithNameOption("wizardSpell", new SpecialEffectFactory());
}

