package com.balancedbytes.games.ffb.json;

import com.balancedbytes.games.ffb.InjuryTypeFactory;
import com.balancedbytes.games.ffb.PassingDistanceFactory;
import com.balancedbytes.games.ffb.PlayerActionFactory;
import com.balancedbytes.games.ffb.ReRollSourceFactory;
import com.balancedbytes.games.ffb.SeriousInjuryFactory;
import com.balancedbytes.games.ffb.SkillFactory;
import com.balancedbytes.games.ffb.SoundIdFactory;
import com.balancedbytes.games.ffb.SpecialEffectFactory;
import com.balancedbytes.games.ffb.net.NetCommandIdFactory;
import com.balancedbytes.games.ffb.report.ReportIdFactory;

public interface IJsonOption {
    JsonStringOption ACTING_PLAYER_ID = new JsonStringOption("actingPlayerId");
    JsonObjectOption ANIMATION = new JsonObjectOption("animation");
    JsonBooleanOption ARMOR_BROKEN = new JsonBooleanOption("armorBroken");
    JsonArrayOption ARMOR_MODIFIERS = new JsonArrayOption("armorModifiers");
    JsonIntArrayOption ARMOR_ROLL = new JsonIntArrayOption("armorRoll");
    JsonStringOption ATTACKER_ID = new JsonStringOption("attackerId");
    JsonIntArrayOption BLOCK_ROLL = new JsonIntArrayOption("blockRoll");
    JsonIntOption BLOODWEISER_BABES = new JsonIntOption("bloodweiserBabes");
    JsonBooleanOption BOMB = new JsonBooleanOption("bomb");
    JsonIntArrayOption CASUALTY_ROLL = new JsonIntArrayOption("casualtyRoll");
    JsonIntArrayOption CASUALTY_ROLL_DECAY = new JsonIntArrayOption("casualtyRollDecay");
    JsonStringOption CHOOSING_TEAM_ID = new JsonStringOption("choosingTeamId");
    JsonStringOption COACH = new JsonStringOption("coach");
    JsonArrayOption COMMAND_ARRAY = new JsonArrayOption("commandArray");
    JsonIntOption COMMAND_NR = new JsonIntOption("commandNr");
    JsonEnumWithNameOption CONFUSION_SKILL = new JsonEnumWithNameOption("confusionSkill", new SkillFactory());
    JsonStringOption DEFENDER_ID = new JsonStringOption("defenderId");
    JsonBooleanOption EXHAUSTED = new JsonBooleanOption("exhausted");
    JsonIntOption FAME_AWAY = new JsonIntOption("fameAway");
    JsonIntOption FAME_HOME = new JsonIntOption("fameHome");
    JsonIntOption FAN_FACTOR_MODIFIER_AWAY = new JsonIntOption("fanFactorModifierAway");
    JsonIntOption FAN_FACTOR_MODIFIER_HOME = new JsonIntOption("fanFactorModifierHome");
    JsonIntArrayOption FAN_FACTOR_ROLL_AWAY = new JsonIntArrayOption("fanFactorRollAway");
    JsonIntArrayOption FAN_FACTOR_ROLL_HOME = new JsonIntArrayOption("fanFactorRollHome");
    JsonBooleanOption FUMBLE = new JsonBooleanOption("fumble");
    JsonObjectOption GAME = new JsonObjectOption("game");
    JsonLongOption GAME_ID = new JsonLongOption("gameId");
    JsonLongOption GAME_TIME = new JsonLongOption("gameTime");
    JsonBooleanOption HAIL_MARY_PASS = new JsonBooleanOption("hailMaryPass");
    JsonArrayOption HEAT_EXHAUSTION_ARRAY = new JsonArrayOption("heatExhaustionArray");
    JsonPlayerStateOption INJURY = new JsonPlayerStateOption("injury");
    JsonPlayerStateOption INJURY_DECAY = new JsonPlayerStateOption("injuryDecay");
    JsonArrayOption INJURY_MODIFIERS = new JsonArrayOption("injuryModifiers");
    JsonIntArrayOption INJURY_ROLL = new JsonIntArrayOption("injuryRoll");
    JsonEnumWithNameOption INJURY_TYPE = new JsonEnumWithNameOption("injuryType", new InjuryTypeFactory());
    JsonArrayOption KNOCKOUT_RECOVERY_ARRAY = new JsonArrayOption("knockoutRecoveryArray");
    JsonIntArrayOption MASTER_CHEF_ROLL = new JsonIntArrayOption("masterChefRoll");
    JsonIntOption MINIMUM_ROLL = new JsonIntOption("minimumRoll");
    JsonEnumWithNameOption NET_COMMAND_ID = new JsonEnumWithNameOption("netCommandId", new NetCommandIdFactory());
    JsonEnumWithNameOption PASSING_DISTANCE = new JsonEnumWithNameOption("passingDistance", new PassingDistanceFactory());
    JsonEnumWithNameOption PLAYER_ACTION = new JsonEnumWithNameOption("playerAction", new PlayerActionFactory());
    JsonArrayOption PLAYER_ARRAY = new JsonArrayOption("playerArray");
    JsonStringOption PLAYER_ID = new JsonStringOption("playerId");
    JsonStringOption PLAYER_ID_TOUCHDOWN = new JsonStringOption("playerIdTouchdown");
    JsonStringArrayOption PLAYER_IDS_HIT = new JsonStringArrayOption("playerIdsHit");
    JsonPlayerStateOption PLAYER_STATE = new JsonPlayerStateOption("playerState");
    JsonBooleanArrayOption PLAYERS_AFFECTED_AWAY = new JsonBooleanArrayOption("playersAffectedAway");
    JsonBooleanArrayOption PLAYERS_AFFECTED_HOME = new JsonBooleanArrayOption("playersAffectedHome");
    JsonStringOption RACE = new JsonStringOption("race");
    JsonBooleanOption RECOVERING = new JsonBooleanOption("recovering");
    JsonIntOption REPLAY_TO_COMMAND_NR = new JsonIntOption("replayToCommandNr");
    JsonEnumWithNameOption REPORT_ID = new JsonEnumWithNameOption("reportId", new ReportIdFactory());
    JsonObjectOption REPORT_LIST = new JsonObjectOption("reportList");
    JsonArrayOption REPORTS = new JsonArrayOption("reports");
    JsonBooleanOption RE_ROLLED = new JsonBooleanOption("reRolled");
    JsonEnumWithNameOption RE_ROLL_SOURCE = new JsonEnumWithNameOption("reRollSource", new ReRollSourceFactory());
    JsonIntOption RE_ROLLS_LEFT_AWAY = new JsonIntOption("reRollsLeftAway");
    JsonIntOption RE_ROLLS_LEFT_HOME = new JsonIntOption("reRollsLeftHome");
    JsonIntOption RE_ROLLS_STOLEN = new JsonIntOption("reRollsStolen");
    JsonIntOption ROLL = new JsonIntOption("roll");
    JsonIntOption ROLL_AWAY = new JsonIntOption("rollAway");
    JsonIntOption ROLL_HOME = new JsonIntOption("rollHome");
    JsonIntArrayOption ROLLS_AWAY = new JsonIntArrayOption("rollsAway");
    JsonIntArrayOption ROLLS_HOME = new JsonIntArrayOption("rollsHome");
    JsonBooleanOption SAFE_THROW_HOLD = new JsonBooleanOption("safeThrowHold");
    JsonEnumWithNameOption SERIOUS_INJURY = new JsonEnumWithNameOption("seriousInjury", new SeriousInjuryFactory());
    JsonEnumWithNameOption SERIOUS_INJURY_DECAY = new JsonEnumWithNameOption("seriousInjuryDecay", new SeriousInjuryFactory());
    JsonEnumWithNameOption SKILL = new JsonEnumWithNameOption("skill", new SkillFactory());
    JsonEnumWithNameOption SOUND = new JsonEnumWithNameOption("sound", new SoundIdFactory());
    JsonEnumWithNameOption SPECIAL_EFFECT = new JsonEnumWithNameOption("specialEffect", new SpecialEffectFactory());
    JsonIntArrayOption SPECTATOR_ROLL_AWAY = new JsonIntArrayOption("spectatorRollAway");
    JsonIntArrayOption SPECTATOR_ROLL_HOME = new JsonIntArrayOption("spectatorRollHome");
    JsonIntOption SPECTATORS_AWAY = new JsonIntOption("spectatorsAway");
    JsonIntOption SPECTATORS_HOME = new JsonIntOption("spectatorsHome");
    JsonIntOption STRENGTH = new JsonIntOption("strength");
    JsonBooleanOption SUCCESSFUL = new JsonBooleanOption("successful");
    JsonObjectOption TEAM_AWAY = new JsonObjectOption("teamAway");
    JsonObjectOption TEAM_HOME = new JsonObjectOption("teamHome");
    JsonStringOption TEAM_ID = new JsonStringOption("teamId");
    JsonStringOption TEAM_NAME = new JsonStringOption("teamName");
    JsonIntArrayOption TENTACLE_ROLL = new JsonIntArrayOption("tentacleRoll");
    JsonStringOption THROWN_PLAYER_ID = new JsonStringOption("thrownPlayerId");
    JsonIntOption TOTAL_NR_OF_COMMANDS = new JsonIntOption("totalNrOfCommands");
    JsonLongOption TURN_TIME = new JsonLongOption("turnTime");
    JsonIntOption WINNINGS_AWAY = new JsonIntOption("winningsAway");
    JsonIntOption WINNINGS_HOME = new JsonIntOption("winningsHome");
    JsonIntOption WINNINGS_ROLL_AWAY = new JsonIntOption("winningsRollAway");
    JsonIntOption WINNINGS_ROLL_HOME = new JsonIntOption("winningsRollHome");
}

